# netlify.toml (Versión Corregida)

[build]
  # 1. Entra en esta carpeta para empezar
  base = "frontend/"

  # 2. Ejecuta este comando aquí dentro
  command = "npm run build"

  # 3. La carpeta a publicar (relativa a 'base') es 'dist'
  publish = "dist/"

# Regla para que las rutas de React funcionen bien
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200