# Archivo de configuraci칩n para Netlify

[build]
  # Comando para construir tu sitio de Vite
  command = "npm run build"

  # Directorio que se debe publicar. Vite lo crea en 'dist'.
  publish = "frontend/dist/"

  # Directorio base donde est치 el c칩digo de tu frontend
  base = "frontend/"

# Regla de redirecci칩n para que las rutas de React (React Router) funcionen
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200